//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaculdadeSI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public class Avaliacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Avaliacao()
        {
            this.AvaliacaoPerguntas = new HashSet<AvaliacaoPergunta>();
            this.AvaliacaoRespostas = new HashSet<AvaliacaoResposta>();
            this.Pergunta = new List<Pergunta>();
        }
    
        public int IdAvaliacao { get; set; }

        //[Required]
        //[DisplayName("Título da avaliação")]
        public string Titulo { get; set; }

        public string DescricaoAvaliacao { get; set; }
        
        //[Required]
        //[DisplayName("Data inicial")]
        public Nullable<DateTime> StartDate { get; set; }

        //[Required]
        //[DisplayName("Data final")]
        public Nullable<DateTime> EndDate { get; set; }

        //[Required]
        //[DisplayName("Criador")]
        public int IdUsuario { get; set; }

        //[Required]
        //[DisplayName("Perfil")]
        public int IdPerfil { get; set; }

        //[Required]
        //[DisplayName("Status")]
        public Nullable<bool> AvaliacaoStatus { get; set; }


        public virtual Perfil Perfil { get; set; }

        public virtual Usuario Usuario { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvaliacaoPergunta> AvaliacaoPerguntas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvaliacaoResposta> AvaliacaoRespostas { get; set; }

        public virtual List<Pergunta> Pergunta { get; set; }

        public virtual List<TipoResposta> TipoResposta {get; set;}





    }
}
